/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommerceCreateNestedManyWithoutUtilisateursInput } from "./CommerceCreateNestedManyWithoutUtilisateursInput";
import {
  ValidateNested,
  IsOptional,
  IsBoolean,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { NotificationCreateNestedManyWithoutUtilisateursInput } from "./NotificationCreateNestedManyWithoutUtilisateursInput";

@InputType()
class UtilisateurCreateInput {
  @ApiProperty({
    required: false,
    type: () => CommerceCreateNestedManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => CommerceCreateNestedManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => CommerceCreateNestedManyWithoutUtilisateursInput, {
    nullable: true,
  })
  commerceItems?: CommerceCreateNestedManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  confirmationEmail?: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  motDePasse?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nom?: string | null;

  @ApiProperty({
    required: false,
    type: () => NotificationCreateNestedManyWithoutUtilisateursInput,
  })
  @ValidateNested()
  @Type(() => NotificationCreateNestedManyWithoutUtilisateursInput)
  @IsOptional()
  @Field(() => NotificationCreateNestedManyWithoutUtilisateursInput, {
    nullable: true,
  })
  notifications?: NotificationCreateNestedManyWithoutUtilisateursInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  telephone?: string | null;
}

export { UtilisateurCreateInput as UtilisateurCreateInput };
