/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CommerceWhereUniqueInput } from "../../commerce/base/CommerceWhereUniqueInput";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumPanierMystereEtat } from "./EnumPanierMystereEtat";
import { StringFilter } from "../../util/StringFilter";
import { FloatNullableFilter } from "../../util/FloatNullableFilter";
import { VenteListRelationFilter } from "../../vente/base/VenteListRelationFilter";

@InputType()
class PanierMystereWhereInput {
  @ApiProperty({
    required: false,
    type: () => CommerceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CommerceWhereUniqueInput)
  @IsOptional()
  @Field(() => CommerceWhereUniqueInput, {
    nullable: true,
  })
  commerce?: CommerceWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumPanierMystereEtat,
  })
  @IsEnum(EnumPanierMystereEtat)
  @IsOptional()
  @Field(() => EnumPanierMystereEtat, {
    nullable: true,
  })
  etat?: "Option1";

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nom?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: FloatNullableFilter,
  })
  @Type(() => FloatNullableFilter)
  @IsOptional()
  @Field(() => FloatNullableFilter, {
    nullable: true,
  })
  prix?: FloatNullableFilter;

  @ApiProperty({
    required: false,
    type: () => VenteListRelationFilter,
  })
  @ValidateNested()
  @Type(() => VenteListRelationFilter)
  @IsOptional()
  @Field(() => VenteListRelationFilter, {
    nullable: true,
  })
  ventes?: VenteListRelationFilter;
}

export { PanierMystereWhereInput as PanierMystereWhereInput };
