/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MethodePaiementService } from "../methodePaiement.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MethodePaiementCreateInput } from "./MethodePaiementCreateInput";
import { MethodePaiement } from "./MethodePaiement";
import { MethodePaiementFindManyArgs } from "./MethodePaiementFindManyArgs";
import { MethodePaiementWhereUniqueInput } from "./MethodePaiementWhereUniqueInput";
import { MethodePaiementUpdateInput } from "./MethodePaiementUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MethodePaiementControllerBase {
  constructor(
    protected readonly service: MethodePaiementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: MethodePaiement })
  @nestAccessControl.UseRoles({
    resource: "MethodePaiement",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMethodePaiement(
    @common.Body() data: MethodePaiementCreateInput
  ): Promise<MethodePaiement> {
    return await this.service.createMethodePaiement({
      data: data,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [MethodePaiement] })
  @ApiNestedQuery(MethodePaiementFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "MethodePaiement",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async methodePaiements(
    @common.Req() request: Request
  ): Promise<MethodePaiement[]> {
    const args = plainToClass(MethodePaiementFindManyArgs, request.query);
    return this.service.methodePaiements({
      ...args,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: MethodePaiement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MethodePaiement",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async methodePaiement(
    @common.Param() params: MethodePaiementWhereUniqueInput
  ): Promise<MethodePaiement | null> {
    const result = await this.service.methodePaiement({
      where: params,
      select: {
        createdAt: true,
        id: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: MethodePaiement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MethodePaiement",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMethodePaiement(
    @common.Param() params: MethodePaiementWhereUniqueInput,
    @common.Body() data: MethodePaiementUpdateInput
  ): Promise<MethodePaiement | null> {
    try {
      return await this.service.updateMethodePaiement({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: MethodePaiement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "MethodePaiement",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMethodePaiement(
    @common.Param() params: MethodePaiementWhereUniqueInput
  ): Promise<MethodePaiement | null> {
    try {
      return await this.service.deleteMethodePaiement({
        where: params,
        select: {
          createdAt: true,
          id: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
