/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsEnum } from "class-validator";
import { FeedbackCreateNestedManyWithoutCommerceItemsInput } from "./FeedbackCreateNestedManyWithoutCommerceItemsInput";
import { Type } from "class-transformer";
import { PanierMystereCreateNestedManyWithoutCommerceItemsInput } from "./PanierMystereCreateNestedManyWithoutCommerceItemsInput";
import { EnumCommerceTypeField } from "./EnumCommerceTypeField";
import { UtilisateurWhereUniqueInput } from "../../utilisateur/base/UtilisateurWhereUniqueInput";

@InputType()
class CommerceCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  adresse?: string | null;

  @ApiProperty({
    required: false,
    type: () => FeedbackCreateNestedManyWithoutCommerceItemsInput,
  })
  @ValidateNested()
  @Type(() => FeedbackCreateNestedManyWithoutCommerceItemsInput)
  @IsOptional()
  @Field(() => FeedbackCreateNestedManyWithoutCommerceItemsInput, {
    nullable: true,
  })
  feedbacks?: FeedbackCreateNestedManyWithoutCommerceItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nom?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nomJuridique?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  numTva?: string | null;

  @ApiProperty({
    required: false,
    type: () => PanierMystereCreateNestedManyWithoutCommerceItemsInput,
  })
  @ValidateNested()
  @Type(() => PanierMystereCreateNestedManyWithoutCommerceItemsInput)
  @IsOptional()
  @Field(() => PanierMystereCreateNestedManyWithoutCommerceItemsInput, {
    nullable: true,
  })
  panierMysteres?: PanierMystereCreateNestedManyWithoutCommerceItemsInput;

  @ApiProperty({
    required: false,
    enum: EnumCommerceTypeField,
  })
  @IsEnum(EnumCommerceTypeField)
  @IsOptional()
  @Field(() => EnumCommerceTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => UtilisateurWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UtilisateurWhereUniqueInput)
  @IsOptional()
  @Field(() => UtilisateurWhereUniqueInput, {
    nullable: true,
  })
  utilisateur?: UtilisateurWhereUniqueInput | null;
}

export { CommerceCreateInput as CommerceCreateInput };
