/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested, IsEnum } from "class-validator";
import { FeedbackUpdateManyWithoutCommerceItemsInput } from "./FeedbackUpdateManyWithoutCommerceItemsInput";
import { Type } from "class-transformer";
import { PanierMystereUpdateManyWithoutCommerceItemsInput } from "./PanierMystereUpdateManyWithoutCommerceItemsInput";
import { EnumCommerceTypeField } from "./EnumCommerceTypeField";
import { UtilisateurWhereUniqueInput } from "../../utilisateur/base/UtilisateurWhereUniqueInput";

@InputType()
class CommerceUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  adresse?: string | null;

  @ApiProperty({
    required: false,
    type: () => FeedbackUpdateManyWithoutCommerceItemsInput,
  })
  @ValidateNested()
  @Type(() => FeedbackUpdateManyWithoutCommerceItemsInput)
  @IsOptional()
  @Field(() => FeedbackUpdateManyWithoutCommerceItemsInput, {
    nullable: true,
  })
  feedbacks?: FeedbackUpdateManyWithoutCommerceItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nom?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nomJuridique?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  numTva?: string | null;

  @ApiProperty({
    required: false,
    type: () => PanierMystereUpdateManyWithoutCommerceItemsInput,
  })
  @ValidateNested()
  @Type(() => PanierMystereUpdateManyWithoutCommerceItemsInput)
  @IsOptional()
  @Field(() => PanierMystereUpdateManyWithoutCommerceItemsInput, {
    nullable: true,
  })
  panierMysteres?: PanierMystereUpdateManyWithoutCommerceItemsInput;

  @ApiProperty({
    required: false,
    enum: EnumCommerceTypeField,
  })
  @IsEnum(EnumCommerceTypeField)
  @IsOptional()
  @Field(() => EnumCommerceTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: () => UtilisateurWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UtilisateurWhereUniqueInput)
  @IsOptional()
  @Field(() => UtilisateurWhereUniqueInput, {
    nullable: true,
  })
  utilisateur?: UtilisateurWhereUniqueInput | null;
}

export { CommerceUpdateInput as CommerceUpdateInput };
