/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsOptional,
  IsDate,
  ValidateNested,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { Feedback } from "../../feedback/base/Feedback";
import { PanierMystere } from "../../panierMystere/base/PanierMystere";
import { EnumCommerceTypeField } from "./EnumCommerceTypeField";
import { Utilisateur } from "../../utilisateur/base/Utilisateur";

@ObjectType()
class Commerce {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  adresse!: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [Feedback],
  })
  @ValidateNested()
  @Type(() => Feedback)
  @IsOptional()
  feedbacks?: Array<Feedback>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nom!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  nomJuridique!: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  numTva!: string | null;

  @ApiProperty({
    required: false,
    type: () => [PanierMystere],
  })
  @ValidateNested()
  @Type(() => PanierMystere)
  @IsOptional()
  panierMysteres?: Array<PanierMystere>;

  @ApiProperty({
    required: false,
    enum: EnumCommerceTypeField,
  })
  @IsEnum(EnumCommerceTypeField)
  @IsOptional()
  @Field(() => EnumCommerceTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => Utilisateur,
  })
  @ValidateNested()
  @Type(() => Utilisateur)
  @IsOptional()
  utilisateur?: Utilisateur | null;
}

export { Commerce as Commerce };
